// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5534.Onabot.subsystems;


import org.usfirst.frc5534.Onabot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

import edu.wpi.first.wpilibj.Counter;
import edu.wpi.first.wpilibj.DigitalInput;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Elevator1 extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private DigitalInput elev1BottomSwitch;
    private DigitalInput elev1TopSwitch;
    private WPI_VictorSPX elev1MotorController;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Counter elev1BottomCounter;
    private Counter elev1TopCounter;

    public Elevator1() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        elev1BottomSwitch = new DigitalInput(0);
        addChild("Elev1 Bottom Switch",elev1BottomSwitch);
        elev1TopSwitch = new DigitalInput(1);
        addChild("Elev1 Top Switch",elev1TopSwitch);
        
        
        elev1MotorController = new WPI_VictorSPX(2);
        
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    elev1BottomCounter = new Counter(elev1BottomSwitch);
    elev1TopCounter = new Counter(elev1TopSwitch);

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Elev1Down());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    /**
     * Run Elevator1 Down
     */
    public void down(){
        elev1MotorController.set(-0.5);
    }

    /**
     * Run Elevator1 Up
     */
    public void up(){
        elev1MotorController.set(0.5);
    }

    public void stop(){
        elev1MotorController.set(0);
    }

    public void initBottomCounter(){
        elev1BottomCounter.reset();
    }

    public void initTopCounter(){
        elev1TopCounter.reset();
    }

    /**
     * isBottomSwitchSet returns true if the counter
     * greater then 0
     */
    public boolean isBottomSwitchSet(){
        return elev1BottomCounter.get() > 0;

    }

    public boolean isTopSwitchSet(){
        return elev1TopCounter.get() > 0;
    }
}

