// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5534.Onabot.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;

import org.usfirst.frc5534.Onabot.RobotMap;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class ElevatorPlatform extends Subsystem {

    private Compressor compressor1;
    private DoubleSolenoid elevatorPlatform;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public ElevatorPlatform() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        compressor1 = new Compressor(RobotMap.kPCMCanID);
        addChild("Compressor 1",compressor1);
        
        
        elevatorPlatform = new DoubleSolenoid(RobotMap.kPCMCanID,
                                              RobotMap.kElevTablePCMForwardPort,
                                              RobotMap.kElevTablePCMBackwardPort);
        addChild("Elevator Platform",elevatorPlatform);
        
    }

    @Override
    public void initDefaultCommand() {

    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }


    public void deployElevator(){
        elevatorPlatform.set(Value.kForward);
    }

    public void retractElevator(){
        elevatorPlatform.set(Value.kReverse);
    }

}

